import type { PalenkeGalleryMedia } from "@/lib/palenke-gallery-media";
import type { ViewerRole } from "@/lib/mock-data";

export const MEDIATECA_UBUNTU_CATEGORIES = [
  { id: "todas", label: "Todas las colecciones" },
  { id: "cc-los-cimarrones", label: "C.C. LOS CIMARRONES" },
  { id: "cc-capitania", label: "C.C. CAPITANIA" },
] as const;

export type MediatecaUbuntuCategoryId = (typeof MEDIATECA_UBUNTU_CATEGORIES)[number]["id"];

export const mediatecaUbuntuGalleryMedia: PalenkeGalleryMedia[] = [
  {
    id: "mediateca-all-img-1802-jpg",
    title: "Fotografía comunitaria en colección general · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_1802.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_1802.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-3473-jpg",
    title: "Fotografía comunitaria en colección general · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3473.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3473.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-3901-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3901.mp4",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3901.mp4",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-8448-jpg",
    title: "Fotografía comunitaria en colección general · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8448.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8448.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-8450-jpg",
    title: "Fotografía comunitaria en colección general · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8450.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8450.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-mvi-7142-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: "/assets/mediateca-ubuntu/all/MVI_7142.MP4",
    mediaUrl: "/assets/mediateca-ubuntu/all/MVI_7142.MP4",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-cc-capitania-img-0643-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0643.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0643.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0650-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0650.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0650.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0677-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0677.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0677.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0685-mov-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0685.MOV.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0685.MOV.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0697-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0697.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0697.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0704-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 6",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0704.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0704.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0719-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 7",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0719.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0719.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1631-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 8",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1631.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1631.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1768-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 9",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1768.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1768.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1784-1-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 10",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1784%20(1).jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1784%20(1).jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-20230714-140314-jpg",
    title: "Memoria territorial en C.C. Capitanía — 14 de julio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_20230714_140314.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_20230714_140314.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-1631-1-jpg",
    title: "Fotografía comunitaria en C.C. Los Cimarrones · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_1631%20(1).jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_1631%20(1).jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230618-162606-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 18 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230618_162606.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230618_162606.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-091735-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_091735.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_091735.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-092517-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_092517.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_092517.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-093657-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093657.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093657.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-093923-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093923.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093923.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100018-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100018.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100018.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100154-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100154.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100154.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100159-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100159.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100159.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-120122-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120122.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120122.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-120136-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120136.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120136.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  }
] as const;

export function getVisibleMediatecaUbuntuGalleryMedia(
  _role: ViewerRole,
  categoryId?: MediatecaUbuntuCategoryId,
): PalenkeGalleryMedia[] {
  return mediatecaUbuntuGalleryMedia.filter((item) => {
    if (item.visibility === "sensitive") return false;
    if (categoryId && categoryId !== "todas" && item.categoryId !== categoryId) return false;
    return true;
  });
}
