import type { PalenkeGalleryMedia } from "@/lib/palenke-gallery-media";
import type { ViewerRole } from "@/lib/mock-data";

const MEDIATECA_VIDEO_POSTER = "/assets/gobierno-propio/memoria-video-poster-2026.png";
/** Working Cloudinary source paired with memoria-video-poster-2026.png (see gobierno-gallery-data). */
const MEDIATECA_COLECCION_GENERAL_VIDEO =
  "https://res.cloudinary.com/dnmjmjdsj/video/upload/v1778886165/image/Generated_Video_May_15_2026_-_6_01PM_yglziv.mp4";
const MEDIATECA_SUPABASE_PUBLIC_BASE =
  "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu";

export const MEDIATECA_UBUNTU_CATEGORIES = [
  { id: "todas", label: "Todas las categorías" },
  { id: "all", label: "Colección general" },
  { id: "areas-bioculturales-2024", label: "Áreas bioculturales de conservación" },
  { id: "areas-de-conservacion", label: "Áreas de conservación" },
  { id: "foro-global-tierra", label: "Foro Global de la Tierra" },
  { id: "instrumento-gobierno-propio", label: "Instrumento de Gobierno Propio" },
  { id: "proyectos-productivos-2024", label: "Soberanía alimentaria" },
  { id: "taller-genero", label: "Generación, género y familia" },
] as const;

export type MediatecaUbuntuCategoryId = (typeof MEDIATECA_UBUNTU_CATEGORIES)[number]["id"];

export const FORO_GLOBAL_TIERRA_SUBCATEGORIES = [
  { id: "apertura-al-foro", label: "Apertura al Foro" },
  { id: "preforo", label: "Preforo" },
  { id: "visita-consejo-mujeres", label: "Visita consejos comunitarios de mujeres" },
  { id: "declaratoria", label: "Declaratoria" },
  { id: "mesa-paralela", label: "Mesa paralela" },
] as const;

export type ForoGlobalTierraSubcategoryId =
  (typeof FORO_GLOBAL_TIERRA_SUBCATEGORIES)[number]["id"];

export const mediatecaUbuntuGalleryMedia: PalenkeGalleryMedia[] = [
  {
    id: "mediateca-all-mvi-7142-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description:
      "Registro audiovisual de la colección general — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Colección general",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: MEDIATECA_VIDEO_POSTER,
    mediaUrl: MEDIATECA_COLECCION_GENERAL_VIDEO,
    playbackMuted: true,
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-areas-de-conservacion-areas-de-conservacion-1-mp4",
    title: "Registro audiovisual en Áreas de conservación · 1",
    section: "Mediateca Ubuntu",
    type: "Video",
    description:
      "Registro audiovisual de la colección Áreas de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: MEDIATECA_VIDEO_POSTER,
    mediaUrl:
      "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-de-conservacion/areas_de_conservacion_1.mp4",
    visibility: "public",
    categoryId: "areas-de-conservacion",
  },
  {
    id: "mediateca-areas-de-conservacion-areas-de-conservacion-2-mp4",
    title: "Registro audiovisual en Áreas de conservación · 2",
    section: "Mediateca Ubuntu",
    type: "Video",
    description:
      "Registro audiovisual de la colección Áreas de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: MEDIATECA_VIDEO_POSTER,
    mediaUrl:
      "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-de-conservacion/areas_de_conservacion_2.mp4",
    visibility: "public",
    categoryId: "areas-de-conservacion",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-video-de-whatsapp-2023-06-29-a-las-15-40-37-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description:
      "Registro audiovisual de la colección general — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Colección general",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "video",
    posterUrl: MEDIATECA_VIDEO_POSTER,
    mediaUrl:
      "/assets/mediateca-ubuntu/cc-diego-luis-cordoba/Video de WhatsApp 2023-06-29 a las 15.40.37.mp4",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8694-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8694.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8694.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8710-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8710.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8710.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8716-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8716.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8716.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8718-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8718.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8718.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8732-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8732.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8732.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8740-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 6",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8740.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8740.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8760-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 7",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8760.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8760.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8767-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 8",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8767.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8767.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8772-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 9",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8772.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8772.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  },
  {
    id: "mediateca-areas-bioculturales-2024-img-8791-jpg",
    title: "Fotografía comunitaria en Áreas bioculturales de conservación · 10",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Áreas bioculturales de conservación — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Áreas bioculturales de conservación",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8791.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/areas-bioculturales-2024/IMG_8791.JPG",
    visibility: "public",
    categoryId: "areas-bioculturales-2024",
  }
,
  {
    id: "mediateca-foro-global-tierra-apertura-al-foro-dsc08200-jpg",
    title: "Fotografía comunitaria en Apertura al Foro · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Apertura al Foro — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08200.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08200.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "apertura-al-foro",
  },
  {
    id: "mediateca-foro-global-tierra-apertura-al-foro-img-8135-jpg",
    title: "Fotografía comunitaria en Apertura al Foro · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Apertura al Foro — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/IMG_8135.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/IMG_8135.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "apertura-al-foro",
  },
  {
    id: "mediateca-foro-global-tierra-apertura-al-foro-img-8158-jpg",
    title: "Fotografía comunitaria en Apertura al Foro · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Apertura al Foro — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/IMG_8158.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/IMG_8158.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "apertura-al-foro",
  },
  {
    id: "mediateca-foro-global-tierra-apertura-al-foro-dsc08220-jpg",
    title: "Fotografía comunitaria en Apertura al Foro · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Apertura al Foro — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08220.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08220.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "apertura-al-foro",
  },
  {
    id: "mediateca-foro-global-tierra-apertura-al-foro-dsc08218-jpg",
    title: "Fotografía comunitaria en Apertura al Foro · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Apertura al Foro — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08218.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/apertura-al-foro/DSC08218.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "apertura-al-foro",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0509-jpg",
    title: "Fotografía comunitaria en Preforo · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0509.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0509.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0470-jpg",
    title: "Fotografía comunitaria en Preforo · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0470.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0470.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0558-jpg",
    title: "Fotografía comunitaria en Preforo · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0558.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0558.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0670-jpg",
    title: "Fotografía comunitaria en Preforo · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0670.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0670.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0561-jpg",
    title: "Fotografía comunitaria en Preforo · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0561.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0561.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0402-jpg",
    title: "Fotografía comunitaria en Preforo · 6",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0402.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0402.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0525-jpg",
    title: "Fotografía comunitaria en Preforo · 7",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0525.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0525.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-preforo-img-0602-jpg",
    title: "Fotografía comunitaria en Preforo · 8",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Preforo — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0602.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/preforo/IMG_0602.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "preforo",
  },
  {
    id: "mediateca-foro-global-tierra-visita-consejo-mujeres-img-0006-jpg",
    title: "Fotografía comunitaria en Visita consejos comunitarios de mujeres · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Visita consejos comunitarios de mujeres — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0006.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0006.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "visita-consejo-mujeres",
  },
  {
    id: "mediateca-foro-global-tierra-visita-consejo-mujeres-img-0012-jpg",
    title: "Fotografía comunitaria en Visita consejos comunitarios de mujeres · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Visita consejos comunitarios de mujeres — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0012.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0012.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "visita-consejo-mujeres",
  },
  {
    id: "mediateca-foro-global-tierra-visita-consejo-mujeres-img-0003-jpg",
    title: "Fotografía comunitaria en Visita consejos comunitarios de mujeres · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Visita consejos comunitarios de mujeres — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0003.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0003.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "visita-consejo-mujeres",
  },
  {
    id: "mediateca-foro-global-tierra-visita-consejo-mujeres-img-0088-jpg",
    title: "Fotografía comunitaria en Visita consejos comunitarios de mujeres · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Visita consejos comunitarios de mujeres — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0088.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0088.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "visita-consejo-mujeres",
  },
  {
    id: "mediateca-foro-global-tierra-visita-consejo-mujeres-img-0102-jpg",
    title: "Fotografía comunitaria en Visita consejos comunitarios de mujeres · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Visita consejos comunitarios de mujeres — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0102.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/visita-consejo-mujeres/IMG_0102.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "visita-consejo-mujeres",
  },
  {
    id: "mediateca-foro-global-tierra-declaratoria-dsc08593-jpg",
    title: "Fotografía comunitaria en Declaratoria · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Declaratoria — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08593.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08593.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "declaratoria",
  },
  {
    id: "mediateca-foro-global-tierra-declaratoria-dsc08604-jpg",
    title: "Fotografía comunitaria en Declaratoria · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Declaratoria — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08604.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08604.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "declaratoria",
  },
  {
    id: "mediateca-foro-global-tierra-declaratoria-dsc08594-jpg",
    title: "Fotografía comunitaria en Declaratoria · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Declaratoria — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08594.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08594.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "declaratoria",
  },
  {
    id: "mediateca-foro-global-tierra-declaratoria-dsc08612-jpg",
    title: "Fotografía comunitaria en Declaratoria · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Declaratoria — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08612.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/declaratoria/DSC08612.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "declaratoria",
  },
  {
    id: "mediateca-foro-global-tierra-mesa-paralela-img-8264-jpg",
    title: "Fotografía comunitaria en Mesa paralela · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Mesa paralela — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8264.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8264.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "mesa-paralela",
  },
  {
    id: "mediateca-foro-global-tierra-mesa-paralela-img-8303-jpg",
    title: "Fotografía comunitaria en Mesa paralela · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Mesa paralela — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8303.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8303.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "mesa-paralela",
  },
  {
    id: "mediateca-foro-global-tierra-mesa-paralela-img-8279-jpg",
    title: "Fotografía comunitaria en Mesa paralela · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Mesa paralela — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8279.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8279.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "mesa-paralela",
  },
  {
    id: "mediateca-foro-global-tierra-mesa-paralela-img-8301-jpg",
    title: "Fotografía comunitaria en Mesa paralela · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Mesa paralela — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8301.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8301.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "mesa-paralela",
  },
  {
    id: "mediateca-foro-global-tierra-mesa-paralela-img-8315-jpg",
    title: "Fotografía comunitaria en Mesa paralela · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de Mesa paralela — Foro Global de la Tierra, memoria comunitaria del Palenke de Pensamiento.",
    territory: "Foro Global de la Tierra",
    council: "Palenke de Pensamiento · PCN",
    year: 2025,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8315.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/foro-global-tierra/mesa-paralela/IMG_8315.JPG",
    visibility: "public",
    categoryId: "foro-global-tierra",
    subcategoryId: "mesa-paralela",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07949-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07949.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07949.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07989-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07989.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07989.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07993-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07993.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07993.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07931-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07931.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07931.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07939-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07939.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07939.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-instrumento-gobierno-propio-dsc07937-jpg",
    title: "Fotografía comunitaria en Instrumento de Gobierno Propio · 6",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Instrumento de Gobierno Propio — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Instrumento de Gobierno Propio",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07937.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/instrumento-gobierno-propio/DSC07937.JPG",
    visibility: "public",
    categoryId: "instrumento-gobierno-propio",
  },
  {
    id: "mediateca-proyectos-productivos-2024-foto-n-7-jpeg",
    title: "Fotografía comunitaria en Soberanía alimentaria · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Soberanía alimentaria — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Soberanía alimentaria",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N7.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N7.jpeg",
    visibility: "public",
    categoryId: "proyectos-productivos-2024",
  },
  {
    id: "mediateca-proyectos-productivos-2024-foto-n-1-jpeg",
    title: "Fotografía comunitaria en Soberanía alimentaria · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Soberanía alimentaria — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Soberanía alimentaria",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N1.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N1.jpeg",
    visibility: "public",
    categoryId: "proyectos-productivos-2024",
  },
  {
    id: "mediateca-proyectos-productivos-2024-foto-n-10-jpeg",
    title: "Fotografía comunitaria en Soberanía alimentaria · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Soberanía alimentaria — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Soberanía alimentaria",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N10.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N10.jpeg",
    visibility: "public",
    categoryId: "proyectos-productivos-2024",
  },
  {
    id: "mediateca-proyectos-productivos-2024-foto-n-9-jpeg",
    title: "Fotografía comunitaria en Soberanía alimentaria · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Soberanía alimentaria — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Soberanía alimentaria",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N9.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N9.jpeg",
    visibility: "public",
    categoryId: "proyectos-productivos-2024",
  },
  {
    id: "mediateca-proyectos-productivos-2024-foto-n-3-jpeg",
    title: "Fotografía comunitaria en Soberanía alimentaria · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Soberanía alimentaria — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Soberanía alimentaria",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N3.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/proyectos-productivos-2024/FOTO-N3.jpeg",
    visibility: "public",
    categoryId: "proyectos-productivos-2024",
  },
  {
    id: "mediateca-taller-genero-foto-n-12-jpeg",
    title: "Fotografía comunitaria en Generación, género y familia · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Generación, género y familia — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Generación, género y familia",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N12.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N12.jpeg",
    visibility: "public",
    categoryId: "taller-genero",
  },
  {
    id: "mediateca-taller-genero-foto-n-15-jpeg",
    title: "Fotografía comunitaria en Generación, género y familia · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Generación, género y familia — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Generación, género y familia",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N15.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N15.jpeg",
    visibility: "public",
    categoryId: "taller-genero",
  },
  {
    id: "mediateca-taller-genero-foto-n-8-jpeg",
    title: "Fotografía comunitaria en Generación, género y familia · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Generación, género y familia — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Generación, género y familia",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N8.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N8.jpeg",
    visibility: "public",
    categoryId: "taller-genero",
  },
  {
    id: "mediateca-taller-genero-foto-n-10-jpeg",
    title: "Fotografía comunitaria en Generación, género y familia · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Generación, género y familia — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Generación, género y familia",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N10.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N10.jpeg",
    visibility: "public",
    categoryId: "taller-genero",
  },
  {
    id: "mediateca-taller-genero-foto-n-7-jpeg",
    title: "Fotografía comunitaria en Generación, género y familia · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección Generación, género y familia — memoria comunitaria del Palenke de Pensamiento.",
    territory: "Generación, género y familia",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N7.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/taller-genero/FOTO-N7.jpeg",
    visibility: "public",
    categoryId: "taller-genero",
  }
] as const;

export function getVisibleMediatecaUbuntuGalleryMedia(
  _role: ViewerRole,
  categoryId?: MediatecaUbuntuCategoryId,
): PalenkeGalleryMedia[] {
  return mediatecaUbuntuGalleryMedia
    .filter((item) => {
      if (item.visibility === "sensitive") return false;
      if (categoryId && categoryId !== "todas" && item.categoryId !== categoryId) return false;
      return true;
    })
    .toSorted((a, b) => {
      if (a.kind === "video" && b.kind !== "video") return -1;
      if (a.kind !== "video" && b.kind === "video") return 1;
      return b.year - a.year;
    });
}