import type { PalenkeGalleryMedia } from "@/lib/palenke-gallery-media";
import type { ViewerRole } from "@/lib/mock-data";

export const MEDIATECA_UBUNTU_CATEGORIES = [
  { id: "todas", label: "Todas las categorías" },
] as const;

export type MediatecaUbuntuCategoryId = (typeof MEDIATECA_UBUNTU_CATEGORIES)[number]["id"];

export const mediatecaUbuntuGalleryMedia: PalenkeGalleryMedia[] = [
  {
    id: "mediateca-all-img-1802-jpg",
    title: "Fotografía comunitaria en colección general · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_1802.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_1802.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-3473-jpg",
    title: "Fotografía comunitaria en colección general · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3473.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3473.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-3901-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3901.mp4",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_3901.mp4",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-8448-jpg",
    title: "Fotografía comunitaria en colección general · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8448.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8448.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-img-8450-jpg",
    title: "Fotografía comunitaria en colección general · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8450.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/all/IMG_8450.JPG",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-all-mvi-7142-mp4",
    title: "Registro audiovisual en colección general",
    section: "Mediateca Ubuntu",
    type: "Video",
    description: "Registro audiovisual de la colección ALL — memoria comunitaria del Palenke de Pensamiento.",
    territory: "ALL",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "video",
    posterUrl: "/assets/mediateca-ubuntu/all/MVI_7142.MP4",
    mediaUrl: "/assets/mediateca-ubuntu/all/MVI_7142.MP4",
    visibility: "public",
    categoryId: "all",
  },
  {
    id: "mediateca-cc-capitania-img-0643-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0643.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0643.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0650-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0650.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0650.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0677-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0677.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0677.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0685-mov-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 4",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0685.MOV.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0685.MOV.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0697-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 5",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0697.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0697.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0704-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 6",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0704.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0704.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-0719-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 7",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0719.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_0719.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1631-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 8",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1631.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1631.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1768-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 9",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1768.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1768.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-1784-1-jpg",
    title: "Fotografía comunitaria en C.C. Capitanía · 10",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1784%20(1).jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_1784%20(1).jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-capitania-img-20230714-140314-jpg",
    title: "Memoria territorial en C.C. Capitanía — 14 de julio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. CAPITANIA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. CAPITANIA",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_20230714_140314.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-capitania/IMG_20230714_140314.jpg",
    visibility: "public",
    categoryId: "cc-capitania",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-1631-1-jpg",
    title: "Fotografía comunitaria en C.C. Los Cimarrones · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_1631%20(1).jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_1631%20(1).jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230618-162606-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 18 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230618_162606.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230618_162606.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-091735-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_091735.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_091735.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-092517-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_092517.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_092517.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-093657-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093657.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093657.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-093923-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093923.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_093923.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100018-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100018.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100018.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100154-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100154.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100154.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-100159-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100159.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_100159.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-120122-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120122.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120122.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-los-cimarrones-img-20230620-120136-jpg",
    title: "Memoria territorial en C.C. Los Cimarrones — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. LOS CIMARRONES — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. LOS CIMARRONES",
    council: "Palenke de Pensamiento · PCN",
    year: 2026,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120136.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-los-cimarrones/IMG_20230620_120136.jpg",
    visibility: "public",
    categoryId: "cc-los-cimarrones",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-imagen-de-whatsapp-2023-06-29-a-las-15-40-38-jpg",
    title: "Fotografía comunitaria en C.C. Diego Luis Córdoba · 1",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.38.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.38.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-imagen-de-whatsapp-2023-06-29-a-las-15-40-384-jpg",
    title: "Fotografía comunitaria en C.C. Diego Luis Córdoba · 2",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.384.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.384.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-imagen-de-whatsapp-2023-06-29-a-las-15-40-39-jpg",
    title: "Fotografía comunitaria en C.C. Diego Luis Córdoba · 3",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.39.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Imagen%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.39.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-img-20230620-060622-jpg",
    title: "Memoria territorial en C.C. Diego Luis Córdoba — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060622.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060622.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-img-20230620-060631-jpg",
    title: "Memoria territorial en C.C. Diego Luis Córdoba — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060631.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060631.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-img-20230620-060924-jpg",
    title: "Memoria territorial en C.C. Diego Luis Córdoba — 20 de junio de 2023",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060924.jpg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/IMG_20230620_060924.jpg",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-cc-diego-luis-cordoba-video-de-whatsapp-2023-06-29-a-las-15-40-37-mp4",
    title: "Registro audiovisual en C.C. Diego Luis Córdoba",
    section: "Mediateca Ubuntu",
    type: "Video",
    description: "Registro audiovisual de la colección C.C. DIEGO LUIS CORDOBA — memoria comunitaria del Palenke de Pensamiento.",
    territory: "C.C. DIEGO LUIS CORDOBA",
    council: "Palenke de Pensamiento · PCN",
    year: 2023,
    kind: "video",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Video%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.37.mp4",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/cc-diego-luis-cordoba/Video%20de%20WhatsApp%202023-06-29%20a%20las%2015.40.37.mp4",
    visibility: "public",
    categoryId: "cc-diego-luis-cordoba",
  },
  {
    id: "mediateca-abcbi-2024-unidad-comunitaria",
    title: "Unidad comunitaria en la creación del sistema biocultural · 2024",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Comunidad en círculo de manos entrelazadas durante el proceso de creación del Sistema de Áreas Bioculturales de Conservación Comunitaria.",
    territory: "Áreas bioculturales de conservación comunitaria · 2024",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8772.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8772.JPG",
    visibility: "public",
    categoryId: "abcbi-2024",
  },
  {
    id: "mediateca-abcbi-2024-mapeo-participativo",
    title: "Mapeo participativo de sitios de interés étnico · 2024",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Revisión colectiva de cartografía comunitaria con ríos, límites territoriales y sitios de interés étnico.",
    territory: "Áreas bioculturales de conservación comunitaria · 2024",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8767.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8767.JPG",
    visibility: "public",
    categoryId: "abcbi-2024",
  },
  {
    id: "mediateca-abcbi-2024-territorio-hidrico",
    title: "Territorio hídrico y ecosistema a conservar · 2024",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Paisaje de cuerpo de agua, vegetación húmeda y canoa comunitaria en el territorio biocultural.",
    territory: "Áreas bioculturales de conservación comunitaria · 2024",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8791.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8791.JPG",
    visibility: "public",
    categoryId: "abcbi-2024",
  },
  {
    id: "mediateca-abcbi-2024-apertura-biocultural-pcn",
    title: "Apertura biocultural con bandera PCN · 2024",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Presentación comunitaria con bandera del Proceso de Comunidades Negras y diseño ceremonial en el suelo.",
    territory: "Áreas bioculturales de conservación comunitaria · 2024",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/abcbi-apertura-biocultural-pcn.jpeg",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/abcbi-apertura-biocultural-pcn.jpeg",
    visibility: "public",
    categoryId: "abcbi-2024",
  },
  {
    id: "mediateca-abcbi-2024-recorrido-territorial",
    title: "Recorrido territorial comunitario · 2024",
    section: "Mediateca Ubuntu",
    type: "Fotografía comunitaria",
    description: "Grupo comunitario en recorrido de campo junto a vía rural, vegetación y cuerpo de agua del territorio.",
    territory: "Áreas bioculturales de conservación comunitaria · 2024",
    council: "Palenke de Pensamiento · PCN",
    year: 2024,
    kind: "image",
    posterUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8778.JPG",
    mediaUrl: "https://xtbdgwlwxslcpyholwuz.supabase.co/storage/v1/object/public/mediateca-ubuntu/abcbi-2024/IMG_8778.JPG",
    visibility: "public",
    categoryId: "abcbi-2024",
  }
] as const;

export function getVisibleMediatecaUbuntuGalleryMedia(
  _role: ViewerRole,
  categoryId?: MediatecaUbuntuCategoryId,
): PalenkeGalleryMedia[] {
  return mediatecaUbuntuGalleryMedia.filter((item) => {
    if (item.visibility === "sensitive") return false;
    if (categoryId && categoryId !== "todas" && item.categoryId !== categoryId) return false;
    return true;
  });
}
