-- Ensures internal (I_) SCITA boards exist with the published embed URLs.
-- Conservación interna: ver también 022_scita_conservacion_internal_dashboard.sql

insert into public.scita_dashboards (
  module_key,
  title,
  short_label,
  description,
  detail_description,
  detail_bullets,
  iframe_title,
  embed_url,
  embed_width,
  embed_height,
  footer_crop_px,
  icon_src,
  visibility,
  status,
  sort_order
) values
(
  'gobierno',
  'Instrumentos de Gobierno Propio (interno)',
  'Gobierno propio',
  'Vista ampliada para equipo Palenke: reglamentos, normas y etnodesarrollo con mayor detalle.',
  'Tablero interno con indicadores y cruces no expuestos en la versión pública. Uso exclusivo para acompañamiento técnico, coordinación territorial y preparación de incidencia con consejos comunitarios.',
  '["Acceso restringido a usuarios internos y administradores.","Incluye desagregaciones y filtros adicionales respecto al tablero público.","No compartir capturas ni enlaces fuera del equipo autorizado."]'::jsonb,
  'I_Instrumentos de Gobierno Propio',
  'https://app.powerbi.com/view?r=eyJrIjoiZTNmNmZjMzAtMTJhOS00YTEzLTljYTAtYjIxNGY0YjRhZGY4IiwidCI6ImNlODUzNmFiLWYzOTktNGZiYS04MWQ1LTgwZDc0ZWVlOTk5ZCIsImMiOjR9',
  600,
  373.5,
  56,
  '/assets/scita/icons/icon-gobierno.png',
  'internal',
  'active',
  11
),
(
  'conservacion',
  'Áreas de Conservación Comunitaria (interno)',
  'Conservación',
  'Vista ampliada para equipo Palenke: presión ambiental, cuencas y figuras de protección con mayor detalle.',
  'Tablero interno con indicadores y cruces no expuestos en la versión pública.',
  '["Acceso restringido a usuarios internos y administradores.","Actualizar embed_url con el enlace I_ de Power BI cuando esté publicado."]'::jsonb,
  'I_Áreas de Conservación Comunitaria',
  'https://app.powerbi.com/view?r=eyJrIjoiNTk3NmZlYmMtN2U2NS00NTFkLWEzOTEtZjAzNTg0ZTZhNjU2IiwidCI6ImNlODUzNmFiLWYzOTktNGZiYS04MWQ1LTgwZDc0ZWVlOTk5ZCIsImMiOjR9',
  600,
  373.5,
  56,
  '/assets/scita/icons/icon-conservacion.png',
  'internal',
  'active',
  21
),
(
  'titulacion',
  'Titulación Colectiva De Comunidades Negras (interno)',
  'Titulación colectiva',
  'Seguimiento detallado de trámites y expedientes para uso del equipo técnico.',
  'Tablero interno para análisis de rezagos, tiempos de gestión y priorización de casos con información no publicada en la versión abierta.',
  '["Acceso restringido a usuarios internos y administradores.","Útil para mesas técnicas y seguimiento jurídico con entidades.","No difundir fuera de canales autorizados del equipo."]'::jsonb,
  'I_Titulación Colectiva De Comunidades Negras',
  'https://app.powerbi.com/view?r=eyJrIjoiZGQ5NTRjNmEtMjlhYi00YzAyLWFiZDgtMWZkZTE4MDFjNDcxIiwidCI6ImNlODUzNmFiLWYzOTktNGZiYS04MWQ1LTgwZDc0ZWVlOTk5ZCIsImMiOjR9',
  600,
  373.5,
  56,
  '/assets/scita/icons/icon-titulacion.png',
  'internal',
  'active',
  31
)
on conflict (module_key, visibility) do update set
  title = excluded.title,
  short_label = excluded.short_label,
  description = excluded.description,
  detail_description = excluded.detail_description,
  detail_bullets = excluded.detail_bullets,
  iframe_title = excluded.iframe_title,
  embed_url = excluded.embed_url,
  embed_width = excluded.embed_width,
  embed_height = excluded.embed_height,
  footer_crop_px = excluded.footer_crop_px,
  icon_src = excluded.icon_src,
  status = excluded.status,
  sort_order = excluded.sort_order,
  updated_at = now();
